# Title: Robust Rank Aggregation (RRA) for Target Prioritization
# Purpose: Integrate multiple ranked lists to identify statistically significant 
# "hub" genes that are consistently dysregulated across cohorts.
# --------------------------------------------------------------------------

library(RobustRankAggreg)

# 1. Load the Ranked Matrix
# This file was generated by the previous 'Dense Ranking' script.
input_file <- "results/Dense_Ranked.csv"
r <- as.matrix(read.csv(input_file, header = TRUE, row.names = 1, check.names = FALSE))

# 2. Execute Robust Rank Aggregation
# N=1840 represents the total number of unique genes/isoforms analyzed.
# RRA is robust to noise and provides a p-value for each aggregated gene.
Ranked_Targets <- aggregateRanks(rmat = r, N = 1840)

# 3. Save Final Prioritized Targets
