# Title: Robust Rank Aggregation (RRA) for Target Prioritization
# Purpose: Integrate multiple ranked lists to identify statistically significant "hub" genes that are consistently dysregulated across cohorts.

library(RobustRankAggreg)

# Load the Ranked Matrix
# The file that was generated by the previous 'Dense_Ranking' script was modified to divide the ranks by number of unique genes/isoforms analyzed, i.e., N
input_file <- "results/Dense_Ranked.csv"
r <- as.matrix(read.csv(input_file, header = TRUE, row.names = 1, check.names = FALSE))

# Execute Robust Rank Aggregation
# N=100 represents the total number of unique genes/isoforms analyzed.
# RRA is robust to noise and provides a p-value for each aggregated gene.
Ranked_Targets <- aggregateRanks(rmat = r, N = 100)

# Save Final Prioritized Targets
# These genes represent high-confidence therapeutic targets for further validation.
write.csv(Ranked_Targets, file = "results/Final_Prioritized_Targets_N1840.csv")

# Preview Top Candidates
head(Ranked_Targets)
